server:
  servlet:
    context-path: /api/smarthomeclima
spring:
  application:
    name: SmartHomeClima
  context:
    component-scan:
      base-package: "it.univaq.disim.seas.smarthomeclima"
  jackson:
    # Date format string or a fully-qualified date format class name. For instance, 'yyyy-MM-dd HH:mm:ss'
    date-format: "yyyy-MM-dd HH:mm:ss"
    # Locale used for formatting
    time-zone: "GMT+8"